import multiprocessing
import subprocess

GPU = '0'

def run_script(command):
    subprocess.run(command, check=True)

commands = []

for model in ['medium_fcn']:
    for fbAtStart in ['0']:
        for seed in ['20']:
            command = []
            command.append('/bin/python3')
            command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            command.append('--gpu')
            command.append(GPU)
            command.append('--epochs')
            command.append('100')
            command.append('--l2_weight')
            command.append('0')
            command.append('--lr')
            command.append('.00001')
            command.append('--seed')
            command.append('101')
            command.append('--neural_balance')
            command.append('1')
            command.append('--neuralFullBalanceAtStart')
            command.append('0')
            commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append(GPU)
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append(seed)
            # command.append('--neural_balance')
            # command.append('1')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('1')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append(GPU)
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append(seed)
            # command.append('--neural_balance')
            # command.append('0')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('1')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('100')
            # command.append('--neural_balance')
            # command.append('1')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('1')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('2')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('100')
            # command.append('--neural_balance')
            # command.append('0')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('1')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('3')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('100')
            # command.append('--neural_balance')
            # command.append('1')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('0')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('4')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('101')
            # command.append('--neural_balance')
            # command.append('0')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('0')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('5')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('100')
            # command.append('--neural_balance')
            # command.append('0')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('0')
            # command.append('--l2_weight')
            # command.append('.00001')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('6')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('100')
            # command.append('--neural_balance')
            # command.append('0')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('1')
            # command.append('--l2_weight')
            # command.append('.00001')
            # commands.append(command)

            # command = []
            # command.append('/bin/python3')
            # command.append('/baldig/proteomics2/ian/Neural-Balance/personalExps/transformer/transformer.py')
            # command.append('--gpu')
            # command.append('7')
            # command.append('--epochs')
            # command.append('200')
            # command.append('--lr')
            # command.append('.0001')
            # command.append('--seed')
            # command.append('100')
            # command.append('--neural_balance')
            # command.append('1')
            # command.append('--neuralFullBalanceAtStart')
            # command.append('0')
            # command.append('--l2_weight')
            # command.append('.00001')
            # commands.append(command)


print(len(commands))

# Create a pool of workers and map commands to the workers
with multiprocessing.Pool(processes=20) as pool:
    pool.map(run_script, commands)